#!/bin/sh

vagrant ssh-config master01.grenier.local > ./ssh_config
vagrant ssh-config master02.grenier.local >> ./ssh_config
vagrant ssh-config master03.grenier.local >> ./ssh_config
# vagrant ssh-config worker01.grenier.local >> ./ssh_config
# vagrant ssh-config worker02.grenier.local >> ./ssh_config
vagrant ssh-config nfs01.grenier.local >> ./ssh_config