- name: Install microk8s
  hosts: [masters, workers]
  become: yes
  tasks:
    - name: Install from snap
      community.general.snap:
        classic: true
        channel: 1.29/stable
        name:
          - microk8s
    - name: Wait ready
      command: microk8s status --wait-ready
    - name: Enable dns
      command: microk8s enable dns
    # - name: Enable ingress
    #   command: microk8s enable ingress
    # - name: Enable cert-manager
    #   command: microk8s enable cert-manager
    # - name: Enable hostpath-storage
    #   command: microk8s enable hostpath-storage