apiVersion: v1
kind: Pod
metadata:
  name: test-win
spec:
  containers:
  - name: test-win
    image: mcr.microsoft.com/windows/nanoserver:ltsc2025
    command: ["cmd", "/c", "echo", "Hello World"]
  nodeSelector:
    kubernetes.io/os: windows