masters:
  hosts:
    master[01:01].k8s.local:
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_common_args: '-F inventory/ssh_config'
workers:
  hosts:
    worker[01:03].k8s.local:
      ansible_ssh_user: vagrant
      ansible_ssh_common_args: '-F inventory/ssh_config'
nfs:
  hosts:
    nfs[01:01].k8s.local:
      ansible_ssh_user: vagrant
      ansible_ssh_common_args: '-F inventory/ssh_config'